In [1]:
import pandas as pd

In [2]:
unemployment_pre = pd.read_csv(r"D:\\Github\\made-ws23\\project\\data\\data\\API_SL.UEM.TOTL.ZS_DS2_en_csv_v2_6299762.csv", skiprows = 3)
crime_pre = pd.read_csv(r"D:\\Github\\made-ws23\\project\\data\\data\\API_VC.IHR.PSRC.P5_DS2_en_csv_v2_6299884.csv", skiprows = 3)

Unemployment data pre-processing

In [3]:
#Finding columns with all null values
unemployment_pre.columns[unemployment_pre.isna().all()].tolist

<bound method IndexOpsMixin.tolist of Index(['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', 'Unnamed: 67'],
      dtype='object')>

In [4]:
#Dropping columns with Null values
unemployment_pre.drop(columns=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990','2022', 'Unnamed: 67'], inplace = True)

In [5]:
#Dropping columns with no significant meaning
unemployment_pre.drop(columns = ['Country Code', 'Indicator Name', 'Indicator Code'], inplace = True)

In [6]:
#Finding rows with all null values
unemployment_pre[unemployment_pre.loc[:, '1991':].isna().all(axis =1)].index

Int64Index([  0,   6,  11,  12,  27,  51,  52,  57,  78,  79,  84,  90,  91,
            108, 110, 124, 125, 137, 147, 149, 155, 164, 179, 188, 212, 225,
            226, 228, 245, 255, 261],
           dtype='int64')

In [7]:
#Dropping rows with all null values
unemployment_pre.drop(index=[0,   6,  11,  12,  27,  51,  52,  57,  78,  79,  84,  90,  91,
            108, 110, 124, 125, 137, 147, 149, 155, 164, 179, 188, 212, 225,
            226, 228, 245, 255, 261], inplace = True)

In [8]:
unemployment_pre

,Country Name,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
1,Africa Eastern and Southern,7.333336,7.318747,7.242705,7.160694,7.063796,7.055998,7.090541,7.060096,7.015271,...,6.599356,6.512784,6.555646,6.707142,6.855589,6.940365,6.913046,7.121663,7.631304,7.920219
2,Afghanistan,8.121000,8.168000,8.123000,8.111000,8.260000,8.165000,8.089000,8.082000,8.070000,...,8.019000,7.949000,7.910000,8.989000,10.086000,11.180000,11.110000,11.085000,11.710000,NaN
3,Africa Western and Central,4.224595,4.335460,4.372125,4.366898,4.348996,4.379537,4.421117,4.454917,4.637773,...,4.167556,3.804447,3.985878,4.241136,4.112958,4.140484,4.201599,4.261414,4.914143,4.873635
4,Angola,4.489000,4.487000,4.531000,4.395000,4.304000,4.274000,4.262000,4.234000,4.206000,...,8.064000,8.834000,9.580000,9.584000,9.586000,9.535000,9.522000,9.481000,10.350000,10.384000
5,Albania,10.307000,30.015000,25.258000,20.840000,14.611000,13.931000,16.876000,20.047000,20.840000,...,13.380000,15.870000,18.050000,17.190000,15.420000,13.620000,12.300000,11.470000,13.067000,12.683000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Samoa,2.100000,2.385000,2.632000,3.040000,3.189000,3.475000,3.909000,4.180000,4.485000,...,8.750000,8.661000,8.720000,8.763000,8.819000,9.400000,9.472000,9.147000,9.793000,9.910000
262,"Yemen, Rep.",8.342000,8.325000,8.365000,8.340000,8.967000,9.595000,10.206000,10.814000,11.460000,...,13.165000,13.264000,13.470000,13.783000,13.407000,13.250000,13.076000,12.978000,13.575000,13.887000
263,South Africa,21.194000,21.159000,20.971000,20.828000,20.750000,20.627000,20.595000,20.573000,20.419000,...,21.790000,22.040000,22.610000,22.870000,24.020000,23.990000,24.220000,25.540000,24.340000,28.770000
264,Zambia,18.900000,19.460000,19.700000,18.679000,16.858000,15.300000,13.638000,12.000000,12.411000,...,7.850000,8.005000,8.133000,8.280000,8.393000,8.520000,5.030000,5.540000,6.030000,6.220000
265,Zimbabwe,4.997000,5.069000,5.010000,4.960000,5.654000,6.236000,6.930000,6.453000,6.000000,...,5.139000,4.994000,4.770000,5.282000,5.796000,6.279000,6.784000,7.370000,7.898000,8.067000

In [39]:
unemployment_pre.isnull().any()

Country Name    False
1991            False
1992            False
1993            False
1994            False
1995            False
1996            False
1997            False
1998            False
1999            False
2000            False
2001            False
2002            False
2003            False
2004            False
2005            False
2006            False
2007            False
2008            False
2009            False
2010            False
2011            False
2012            False
2013            False
2014            False
2015            False
2016            False
2017            False
2018            False
2019            False
2020            False
2021             True
dtype: bool

In [10]:
#transpose
unemployment_pre.transpose()

,1,2,3,4,5,7,8,9,10,13,...,254,256,257,258,259,260,262,263,264,265
Country Name,Africa Eastern and Southern,Afghanistan,Africa Western and Central,Angola,Albania,Arab World,United Arab Emirates,Argentina,Armenia,Australia,...,"Venezuela, RB",Virgin Islands (U.S.),Viet Nam,Vanuatu,World,Samoa,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
1991,7.333336,8.121,4.224595,4.489,10.307,11.663443,1.887,5.44,1.6,9.58,...,9.45,12.016,2.124,1.734,4.935354,2.1,8.342,21.194,18.9,4.997
1992,7.318747,8.168,4.33546,4.487,30.015,11.950448,1.858,6.36,1.8,10.73,...,7.69,12.275,1.938,1.751,5.082678,2.385,8.325,21.159,19.46,5.069
1993,7.242705,8.123,4.372125,4.531,25.258,12.661873,1.862,10.1,5.3,10.87,...,6.6,12.44,1.989,1.797,5.351496,2.632,8.365,20.971,19.7,5.01
1994,7.160694,8.111,4.366898,4.395,20.84,12.73838,1.81,11.76,6.6,9.72,...,8.56,12.252,1.945,1.622,5.610618,3.04,8.34,20.828,18.679,4.96
1995,7.063796,8.26,4.348996,4.304,14.611,13.216999,1.8,18.8,6.7,8.47,...,10.24,11.832,1.907,1.8,5.777542,3.189,8.967,20.75,16.858,5.654
1996,7.055998,8.165,4.379537,4.274,13.931,12.266322,1.903,17.11,9.3,8.51,...,11.77,11.734,1.93,1.773,5.881647,3.475,9.595,20.627,15.3,6.236
1997,7.090541,8.089,4.421117,4.262,16.876,11.838785,1.983,14.82,10.8,8.36,...,11.16,11.543,2.87,1.719,5.920921,3.909,10.206,20.595,13.638,6.93
1998,7.060096,8.082,4.454917,4.234,20.047,11.848019,2.147,12.65,9.4,7.68,...,11.15,11.3,2.29,1.808,6.092633,4.18,10.814,20.573,12.0,6.453
1999,7.015271,8.07,4.637773,4.206,20.84,11.9773,2.223,14.05,11.2,6.87,...,14.53,10.923,2.33,1.832,6.233896,4.485,11.46,20.419,12.411,6.0
2000,6.939536,8.054,4.666423,4.163,19.028,12.447846,2.25,15.0,11.055,6.28,...,13.99,10.5,2.26,1.708,6.071096,4.664,11.558,20.266,12.93,5.688
2001,6.850376,8.04,4.581781,4.119,18.575,12.324,2.501,17.32,10.933,6.74,...,13.04,10.6,2.76,1.932,6.179645,4.96,11.718,20.217,13.503,5.34
2002,6.803537,8.186,4.448733,4.043,17.895,12.330085,2.654,19.59,10.81,6.37,...,16.17,10.837,2.12,1.983,6.423977,5.099,11.845,20.088,14.131,5.069
2003,6.741241,8.122,4.405969,4.043,16.989,12.254294,2.751,15.36,10.625,5.93,...,16.78,11.164,2.25,1.753,6.541302,5.159,11.977,20.015,14.686,4.774
2004,6.535173,8.053,4.352562,3.972,16.31,11.279341,2.904,13.52,10.347,5.39,...,15.07,10.844,2.14,1.763,6.415079,5.22,12.103,19.866,15.294,4.39
2005,6.373503,8.113,4.321496,3.915,15.97,11.121258,3.12,11.51,10.218,5.03,...,10.66,10.769,2.094,1.737,6.337354,5.297,12.21,19.744,15.9,4.546
2006,6.347598,8.054,4.203058,3.882,15.63,10.411185,2.926,10.08,10.001,4.78,...,8.61,10.228,2.086,1.672,6.063916,5.426,12.371,19.635,13.235,4.692
2007,6.283421,8.108,4.14827,3.827,15.97,10.003051,2.86,8.47,9.81,4.38,...,7.28,10.024,2.03,1.799,5.850746,5.359,12.498,19.543,10.576,4.848
2008,6.232561,8.022,4.167443,3.791,13.06,9.698519,2.721,7.84,9.997,4.23,...,6.25,10.112,1.927,1.741,5.869491,5.584,12.623,19.51,7.93,5.075
2009,6.295587,8.082,4.215073,3.78,13.67,9.312897,2.668,8.65,9.894,5.56,...,6.1,11.406,1.74,1.804,6.460703,5.836,12.75,20.51,10.56,5.077
2010,6.933645,8.068,4.235777,9.43,14.09,9.386507,2.464,7.71,10.542,5.21,...,7.11,11.55,1.11,1.85,6.345866,5.731,12.826,23.18,13.19,5.189
2011,6.715358,7.947,4.188828,7.36,13.48,10.474968,2.284,7.18,10.917,5.08,...,6.9,11.826,1.0,1.801,6.191797,5.68,13.249,21.42,10.585,5.37
2012,6.599356,8.019,4.167556,8.064,13.38,10.673545,2.171,7.22,11.298,5.22,...,6.6,11.91,1.03,1.849,6.138764,8.75,13.165,21.79,7.85,5.139
2013,6.512784,7.949,3.804447,8.834,15.87,10.734339,2.032,7.1,11.531,5.66,...,7.54,12.402,1.32,1.859,6.116123,8.661,13.264,22.04,8.005,4.994
2014,6.555646,7.91,3.985878,9.58,18.05,10.856214,1.902,7.27,11.862,6.08,...,6.865,12.475,1.26,1.792,5.980933,8.72,13.47,22.61,8.133,4.77
2015,6.707142,8.989,4.241136,9.584,17.19,10.968219,1.763,7.524,12.177,6.05,...,6.077,12.258,1.85,1.855,6.010182,8.763,13.783,22.87,8.28,5.282
2016,6.855589,10.086,4.112958,9.586,15.42,10.763359,1.64,8.109,12.426,5.71,...,5.32,12.354,1.85,1.749,6.002212,8.819,13.407,24.02,8.393,5.796
2017,6.940365,11.18,4.140484,9.535,13.62,10.91992,2.46,8.35,12.944,5.59,...,5.05,12.053,1.87,1.71,5.872597,9.4,13.25,23.99,8.52,6.279
2018,6.913046,11.11,4.201599,9.522,12.3,10.58334,2.24,9.22,13.21,5.3,...,5.02,12.245,1.16,1.784,5.69821,9.472,13.076,24.22,5.03,6.784
2019,7.121663,11.085,4.261414,9.481,11.47,10.165158,2.33,9.84,12.2,5.16,...,5.092,12.35,1.68,1.757,5.542306,9.147,12.978,25.54,5.54,7.37
2020,7.631304,11.71,4.914143,10.35,13.067,11.348371,4.29,11.46,12.18,6.46,...,7.53,13.255,2.1,2.017,6.897757,9.793,13.575,24.34,6.03,7.898
2021,7.920219,NaN,4.873635,10.384,12.683,11.023694,3.11,8.74,12.729,5.12,...,6.471,13.173,2.38,2.118,6.201248,9.91,13.887,28.77,6.22,8.067

In [11]:
unemployment_pre.describe()

,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,...,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,235.000000,233.000000
mean,7.203454,7.540393,7.960158,8.134804,8.205945,8.362589,8.260554,8.309534,8.442746,8.320795,...,7.992262,8.014859,7.857355,7.766581,7.642313,7.397376,7.142236,6.981620,8.092711,7.790017
std,5.558514,5.852712,5.893973,5.816435,5.893918,5.929165,5.741067,5.692092,5.671484,5.730362,...,5.608178,5.680047,5.538518,5.391665,5.283956,5.132069,5.060026,4.933294,5.168343,5.166036
min,0.600000,0.661000,0.637000,0.645000,0.647000,0.640000,0.610000,0.613000,0.614000,0.611000,...,0.480000,0.250000,0.200000,0.170000,0.150000,0.140000,0.110000,0.100000,0.140000,0.170000
25%,3.005000,3.251000,3.719000,4.010000,4.036000,4.098336,4.092500,4.198602,4.354000,4.133000,...,4.059724,4.080076,4.160535,4.305000,4.187575,3.965525,3.822140,3.765450,4.525500,4.370000
50%,5.804886,5.919228,6.123000,6.550999,7.063796,7.141000,7.090541,7.050980,6.930000,6.682014,...,6.712269,6.512784,6.328231,6.490000,6.010000,5.835599,5.620000,5.542306,6.770000,6.260000
75%,9.764504,10.176000,10.842606,11.095000,10.980617,11.329000,11.015319,11.259500,11.711000,11.319536,...,10.248132,10.140000,10.125750,9.835000,9.655000,9.360000,9.015000,8.736000,10.197892,9.582000
max,29.887000,30.015000,29.745000,30.000000,35.600000,38.800000,36.000000,34.500000,32.400000,32.200000,...,31.200000,29.140000,28.380000,27.690000,26.197000,26.060000,26.260000,26.315000,28.048000,28.770000

# Crime data pre-processing

In [12]:
#Finding columns with all null values
crime_pre.columns[crime_pre.isna().all()].tolist

<bound method IndexOpsMixin.tolist of Index(['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '2022', 'Unnamed: 67'],
      dtype='object')>

In [13]:
#Dropping columns with Null values
crime_pre.drop(columns=['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '2022', 'Unnamed: 67'], inplace = True)

In [14]:
#Dropping columns with no significant meaning
crime_pre.drop(columns = ['Country Code', 'Indicator Name', 'Indicator Code'], inplace = True)

In [15]:
crime_pre

,Country Name,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,NaN,NaN,NaN,NaN,7.787151,NaN,NaN,NaN,2.302370,...,3.917286,5.832037,1.930614,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.100000,NaN,10.500000,10.300000,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393913,NaN,NaN,9.975262,6.692419,6.800695,6.743573,7.180397,6.594439,4.022498
3,Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.300000,NaN,8.100000,8.100000,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.831610,NaN,NaN,4.458235,4.102248,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.968498,2.270620,3.093696,2.387555,2.170532,2.771898,2.573157,1.422763,2.214643,NaN
262,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.492704,5.652914,...,6.162437,6.311147,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,NaN,NaN,NaN,60.009733,61.103416,57.028853,54.070826,54.800028,48.752627,...,30.507084,31.598028,32.532699,33.418340,33.703002,35.903188,36.662249,36.712138,33.964874,41.865728
264,Zambia,8.67969,9.511616,9.007465,9.806217,NaN,NaN,NaN,9.303884,11.142017,...,6.002174,5.690852,5.242158,5.249803,NaN,NaN,NaN,NaN,NaN,NaN
265,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.395217,NaN,NaN,NaN,NaN,NaN,4.876369,5.145035,4.977770,6.139985

In [16]:
# Finding countries where total null values are greater than 5 starting from 1990 to 2021
countries_with_nulls = crime_pre[crime_pre.loc[:, '1991':].isna().sum(axis=1) > 5]

# Drop the countries having NAN values greater than 6
crime_pre_cleaned = crime_pre.drop(countries_with_nulls[countries_with_nulls.sum(axis=1) > 6].index)

# List of remaining countries
remaining_countries = crime_pre_cleaned['Country Name'].tolist()

# Total count of remaining countries
total_remaining_countries = len(remaining_countries)

# Print the results
print("Remaining Countries:")
print(remaining_countries)
print("\nTotal Count of Remaining Countries:", total_remaining_countries)

Remaining Countries:
['Albania', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Benin', 'Bulgaria', 'Bahamas, The', 'Bermuda', 'Brazil', 'Barbados', 'Bhutan', 'Canada', 'Central Europe and the Baltics', 'Channel Islands', "Cote d'Ivoire", 'Congo, Dem. Rep.', 'Congo, Rep.', 'Colombia', 'Comoros', 'Costa Rica', 'Cuba', 'Cayman Islands', 'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Dominican Republic', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Euro area', 'Spain', 'Estonia', 'European Union', 'Finland', 'France', 'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gabon', 'United Kingdom', 'Gibraltar', 'Guinea', 'Gambia, The', 'Guinea-Bissau', 'Equatorial Guinea', 'Greece', 'Guatemala', 'Guyana', 'Hong Kong SAR, China', 'Honduras', 'Croatia', 'Hungary', 'Indonesia', 'India', 'Not classified', 'Ireland', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Kyrgyz Republic', 'Korea, Rep.', 'Lao PDR', 'Libya', 'St. Lucia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao SAR, China', 'Morocco', 'Monaco', 'Moldova', 'Madagascar', 'Mexico', 'Mali', 'Malta', 'Northern Mariana Islands', 'Mauritania', 'Malaysia', 'Nicaragua', 'Netherlands', 'Norway', 'Nauru', 'New Zealand', 'Pakistan', 'Panama', 'Poland', 'Puerto Rico', "Korea, Dem. People's Rep.", 'Qatar', 'Romania', 'Russian Federation', 'Senegal', 'Singapore', 'El Salvador', 'San Marino', 'Somalia', 'Slovak Republic', 'Slovenia', 'Sweden', 'Sint Maarten (Dutch part)', 'Chad', 'East Asia & Pacific (IDA & IBRD countries)', 'Togo', 'Ukraine', 'Uruguay', 'United States', 'St. Vincent and the Grenadines', 'Venezuela, RB', 'Vanuatu', 'South Africa']

Total Count of Remaining Countries: 112

C:\Users\rajsi\AppData\Local\Temp\ipykernel_15600\704241859.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  crime_pre_cleaned = crime_pre.drop(countries_with_nulls[countries_with_nulls.sum(axis=1) > 6].index)

In [17]:
print(crime_pre_cleaned)

                       Country Name       1991       1992       1993  \
5                           Albania        NaN   3.934936   5.786633
10                          Armenia   5.141486   8.532529   7.751603
13                        Australia   1.968608   1.723693   1.888664
14                          Austria   1.328066   1.237116   1.011982
15                       Azerbaijan   4.735836   7.378975   6.175625
..                              ...        ...        ...        ...
251                   United States   9.819916   9.311245   9.477558
253  St. Vincent and the Grenadines  15.960277  15.898041  12.321666
254                   Venezuela, RB  12.370086  15.777427  20.271962
258                         Vanuatu        NaN        NaN        NaN
263                    South Africa        NaN        NaN        NaN

          1994       1995       1996       1997       1998       1999  ...  \
5     3.400123   7.885849   8.314658  40.999238  20.419683  16.582197  ...
10    4.653626   3.491050   3.455700   3.056778   2.869883   2.807211  ...
13    1.797197   1.977448   1.943790   1.977159   1.795538   2.047775  ...
14    1.108960   0.981466   1.244025   0.828408   0.965413   0.750809  ...
15    6.379541   5.615179   5.032015   3.549973   3.482113   2.987120  ...
..         ...        ...        ...        ...        ...        ...  ...
251   8.893766   8.132935   7.303399   6.684400   6.153678   5.559822  ...
253  11.409163  17.517123  20.999121   7.875635  21.022297  12.281294  ...
254  21.870692  20.269336  21.978450  18.339615  19.358556  24.925982  ...
258        NaN        NaN        NaN        NaN        NaN        NaN  ...
263  60.009733  61.103416  57.028853  54.070826  54.800028  48.752627  ...

          2012       2013       2014       2015       2016       2017  \
5     5.428407   4.295095   4.646160   2.220310   2.742043   2.014340
10    2.230289   2.171377   2.491410   2.605438   3.035764   2.454484
13    1.069106   1.060065   1.035383   0.990754   0.938183   0.845861
14    0.960896   0.719379   0.491454   0.509117   0.618097   0.795681
15    2.129549   2.298617   2.422530   2.139204   1.694024   1.807067
..         ...        ...        ...        ...        ...        ...
251   4.691596   4.483442   4.398294   4.892982   5.321656   5.243924
253        NaN        NaN        NaN        NaN  37.749204  36.949838
254  54.536029        NaN  63.027315  51.274634  56.623849  47.982175
258        NaN        NaN        NaN        NaN        NaN        NaN
263  30.507084  31.598028  32.532699  33.418340  33.703002  35.903188

          2018       2019       2020       2021
5     2.294046   2.261748   2.127772   2.311969
10    1.762700   2.588100   1.853430   2.185617
13    0.884735   0.887323   0.860925   0.744567
14    0.972794   0.867123   0.729699   0.728530
15    1.940405   1.641787   2.236277   1.910212
..         ...        ...        ...        ...
251   4.929848   4.985947   6.420751   6.807466
253  32.294679  18.108431  31.538958  30.671318
254        NaN  40.984846  29.427401  19.305056
258        NaN   0.657021   0.320837        NaN
263  36.662249  36.712138  33.964874  41.865728

[112 rows x 32 columns]

In [18]:
# Fill NaN values in columns with their mean
crime_pre_cleaned_filled = crime_pre_cleaned.fillna(crime_pre_cleaned.mean())

# Print the cleaned and filled data
print("Cleaned and Filled Crime Dataset:")
print(crime_pre_cleaned_filled)

Cleaned and Filled Crime Dataset:
                       Country Name       1991       1992       1993  \
5                           Albania   7.469486   3.934936   5.786633
10                          Armenia   5.141486   8.532529   7.751603
13                        Australia   1.968608   1.723693   1.888664
14                          Austria   1.328066   1.237116   1.011982
15                       Azerbaijan   4.735836   7.378975   6.175625
..                              ...        ...        ...        ...
251                   United States   9.819916   9.311245   9.477558
253  St. Vincent and the Grenadines  15.960277  15.898041  12.321666
254                   Venezuela, RB  12.370086  15.777427  20.271962
258                         Vanuatu   7.469486   8.189933   8.509661
263                    South Africa   7.469486   8.189933   8.509661

          1994       1995       1996       1997       1998       1999  ...  \
5     3.400123   7.885849   8.314658  40.999238  20.419683  16.582197  ...
10    4.653626   3.491050   3.455700   3.056778   2.869883   2.807211  ...
13    1.797197   1.977448   1.943790   1.977159   1.795538   2.047775  ...
14    1.108960   0.981466   1.244025   0.828408   0.965413   0.750809  ...
15    6.379541   5.615179   5.032015   3.549973   3.482113   2.987120  ...
..         ...        ...        ...        ...        ...        ...  ...
251   8.893766   8.132935   7.303399   6.684400   6.153678   5.559822  ...
253  11.409163  17.517123  20.999121   7.875635  21.022297  12.281294  ...
254  21.870692  20.269336  21.978450  18.339615  19.358556  24.925982  ...
258  10.776662  10.797970  10.087810   9.990271   8.835399   8.600639  ...
263  60.009733  61.103416  57.028853  54.070826  54.800028  48.752627  ...

          2012       2013       2014       2015       2016       2017  \
5     5.428407   4.295095   4.646160   2.220310   2.742043   2.014340
10    2.230289   2.171377   2.491410   2.605438   3.035764   2.454484
13    1.069106   1.060065   1.035383   0.990754   0.938183   0.845861
14    0.960896   0.719379   0.491454   0.509117   0.618097   0.795681
15    2.129549   2.298617   2.422530   2.139204   1.694024   1.807067
..         ...        ...        ...        ...        ...        ...
251   4.691596   4.483442   4.398294   4.892982   5.321656   5.243924
253   8.910891   8.430357   8.631802   8.224460  37.749204  36.949838
254  54.536029   8.430357  63.027315  51.274634  56.623849  47.982175
258   8.910891   8.430357   8.631802   8.224460   8.945892   8.701136
263  30.507084  31.598028  32.532699  33.418340  33.703002  35.903188

          2018       2019       2020       2021
5     2.294046   2.261748   2.127772   2.311969
10    1.762700   2.588100   1.853430   2.185617
13    0.884735   0.887323   0.860925   0.744567
14    0.972794   0.867123   0.729699   0.728530
15    1.940405   1.641787   2.236277   1.910212
..         ...        ...        ...        ...
251   4.929848   4.985947   6.420751   6.807466
253  32.294679  18.108431  31.538958  30.671318
254   7.785687  40.984846  29.427401  19.305056
258   7.785687   0.657021   0.320837   8.096185
263  36.662249  36.712138  33.964874  41.865728

[112 rows x 32 columns]

C:\Users\rajsi\AppData\Local\Temp\ipykernel_15600\225844550.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  crime_pre_cleaned_filled = crime_pre_cleaned.fillna(crime_pre_cleaned.mean())

In [37]:
#transpose
crime_pre_cleaned_filled.isnull().all()

Country Name    False
1991            False
1992            False
1993            False
1994            False
1995            False
1996            False
1997            False
1998            False
1999            False
2000            False
2001            False
2002            False
2003            False
2004            False
2005            False
2006            False
2007            False
2008            False
2009            False
2010            False
2011            False
2012            False
2013            False
2014            False
2015            False
2016            False
2017            False
2018            False
2019            False
2020            False
2021            False
dtype: bool

In [20]:
crime_pre_cleaned_filled.shape

(112, 32)

# removing extra countries from unemployment data to sync with crime data

In [21]:

remaining_countries = ['Albania', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Benin', 'Bulgaria', 'Bahamas, The', 'Bermuda', 'Brazil', 'Barbados', 'Bhutan', 'Canada', 'Central Europe and the Baltics', 'Channel Islands', "Cote d'Ivoire", 'Congo, Dem. Rep.', 'Congo, Rep.', 'Colombia', 'Comoros', 'Costa Rica', 'Cuba', 'Cayman Islands', 'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Dominican Republic', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Euro area', 'Spain', 'Estonia', 'European Union', 'Finland', 'France', 'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gabon', 'United Kingdom', 'Gibraltar', 'Guinea', 'Gambia, The', 'Guinea-Bissau', 'Equatorial Guinea', 'Greece', 'Guatemala', 'Guyana', 'Hong Kong SAR, China', 'Honduras', 'Croatia', 'Hungary', 'Indonesia', 'India', 'Not classified', 'Ireland', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Kyrgyz Republic', 'Korea, Rep.', 'Lao PDR', 'Libya', 'St. Lucia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao SAR, China', 'Morocco', 'Monaco', 'Moldova', 'Madagascar', 'Mexico', 'Mali', 'Malta', 'Northern Mariana Islands', 'Mauritania', 'Malaysia', 'Nicaragua', 'Netherlands', 'Norway', 'Nauru', 'New Zealand', 'Pakistan', 'Panama', 'Poland', 'Puerto Rico', "Korea, Dem. People's Rep.", 'Qatar', 'Romania', 'Russian Federation', 'Senegal', 'Singapore', 'El Salvador', 'San Marino', 'Somalia', 'Slovak Republic', 'Slovenia', 'Sweden', 'Sint Maarten (Dutch part)', 'Chad', 'East Asia & Pacific (IDA & IBRD countries)', 'Togo', 'Ukraine', 'Uruguay', 'United States', 'St. Vincent and the Grenadines', 'Venezuela, RB', 'Vanuatu', 'South Africa']
# Filter the rows for the remaining countries
unemployment_remaining_countries = unemployment_pre[unemployment_pre['Country Name'].isin(remaining_countries)]

# Print the DataFrame for remaining countries
print("Unemployment Data for Remaining Countries:")
print(unemployment_remaining_countries)

Unemployment Data for Remaining Countries:
                       Country Name    1991    1992    1993    1994    1995  \
5                           Albania  10.307  30.015  25.258  20.840  14.611
10                          Armenia   1.600   1.800   5.300   6.600   6.700
13                        Australia   9.580  10.730  10.870   9.720   8.470
14                          Austria   3.420   3.590   4.250   3.540   4.340
15                       Azerbaijan   0.900   1.800   4.500   6.300   7.200
..                              ...     ...     ...     ...     ...     ...
251                   United States   6.800   7.500   6.900   6.120   5.650
253  St. Vincent and the Grenadines  19.770  19.734  19.802  20.185  20.059
254                   Venezuela, RB   9.450   7.690   6.600   8.560  10.240
258                         Vanuatu   1.734   1.751   1.797   1.622   1.800
263                    South Africa  21.194  21.159  20.971  20.828  20.750

       1996    1997    1998    1999  ...    2012    2013    2014    2015  \
5    13.931  16.876  20.047  20.840  ...  13.380  15.870  18.050  17.190
10    9.300  10.800   9.400  11.200  ...  11.298  11.531  11.862  12.177
13    8.510   8.360   7.680   6.870  ...   5.220   5.660   6.080   6.050
14    5.280   5.150   5.480   4.700  ...   4.870   5.340   5.620   5.720
15    8.100   9.100  10.000  10.900  ...   5.190   4.970   4.910   4.960
..      ...     ...     ...     ...  ...     ...     ...     ...     ...
251   5.450   5.000   4.510   4.220  ...   8.070   7.370   6.170   5.280
253  20.395  20.471  20.596  20.781  ...  18.893  18.905  18.948  18.969
254  11.770  11.160  11.150  14.530  ...   6.600   7.540   6.865   6.077
258   1.773   1.719   1.808   1.832  ...   1.849   1.859   1.792   1.855
263  20.627  20.595  20.573  20.419  ...  21.790  22.040  22.610  22.870

       2016    2017    2018    2019    2020    2021
5    15.420  13.620  12.300  11.470  13.067  12.683
10   12.426  12.944  13.210  12.200  12.180  12.729
13    5.710   5.590   5.300   5.160   6.460   5.120
14    6.010   5.500   4.850   4.490   5.360   6.180
15    5.000   4.960   4.940   4.850   7.160   5.950
..      ...     ...     ...     ...     ...     ...
251   4.870   4.360   3.900   3.670   8.050   5.350
253  18.978  19.028  19.020  19.090  20.550  20.398
254   5.320   5.050   5.020   5.092   7.530   6.471
258   1.749   1.710   1.784   1.757   2.017   2.118
263  24.020  23.990  24.220  25.540  24.340  28.770

[100 rows x 32 columns]

In [22]:
unemployment_remaining_countries.transpose()

,5,10,13,14,15,18,21,23,29,30,...,229,230,232,248,250,251,253,254,258,263
Country Name,Albania,Armenia,Australia,Austria,Azerbaijan,Benin,Bulgaria,"Bahamas, The",Brazil,Barbados,...,Chad,East Asia & Pacific (IDA & IBRD countries),Togo,Ukraine,Uruguay,United States,St. Vincent and the Grenadines,"Venezuela, RB",Vanuatu,South Africa
1991,10.307,1.6,9.58,3.42,0.9,1.484,11.1,12.17,6.366,22.683,...,0.662,2.402899,3.81,1.9,8.95,6.8,19.77,9.45,1.734,21.194
1992,30.015,1.8,10.73,3.59,1.8,1.51,15.3,14.81,6.42,22.94,...,0.661,2.36062,3.861,1.9,8.96,7.5,19.734,7.69,1.751,21.159
1993,25.258,5.3,10.87,4.25,4.5,1.396,16.4,12.72,6.03,24.54,...,0.7,2.616372,3.977,2.0,8.35,6.9,19.802,6.6,1.797,20.971
1994,20.84,6.6,9.72,3.54,6.3,1.358,12.8,13.83,6.47,22.98,...,0.675,2.920314,3.764,2.0,9.04,6.12,20.185,8.56,1.622,20.828
1995,14.611,6.7,8.47,4.34,7.2,1.237,11.1,10.83,7.09,19.66,...,0.708,3.001046,3.845,5.62,10.02,5.65,20.059,10.24,1.8,20.75
1996,13.931,9.3,8.51,5.28,8.1,1.175,12.5,11.46,8.03,14.71,...,0.724,3.110923,3.864,7.65,11.93,5.45,20.395,11.77,1.773,20.627
1997,16.876,10.8,8.36,5.15,9.1,1.083,13.7,9.76,9.0,14.61,...,0.737,3.206951,3.847,8.93,11.44,5.0,20.471,11.16,1.719,20.595
1998,20.047,9.4,7.68,5.48,10.0,1.018,12.2,7.65,10.15,12.4,...,0.753,3.376221,4.009,11.32,9.36,4.51,20.596,11.15,1.808,20.573
1999,20.84,11.2,6.87,4.7,10.9,0.927,14.1,7.45,11.13,10.61,...,0.787,3.460092,3.999,11.86,10.47,4.22,20.781,14.53,1.832,20.419
2000,19.028,11.055,6.28,4.69,11.78,0.843,16.22,7.196,10.53,9.35,...,0.806,3.415192,4.057,11.71,12.63,3.99,20.958,13.99,1.708,20.266
2001,18.575,10.933,6.74,4.01,10.91,0.766,19.92,6.87,10.65,9.85,...,0.799,3.850352,4.075,11.06,15.05,4.73,21.1,13.04,1.932,20.217
2002,17.895,10.81,6.37,4.85,10.04,0.69,18.11,9.05,10.64,10.32,...,0.823,4.171569,4.082,10.14,16.65,5.78,20.629,16.17,1.983,20.088
2003,16.989,10.625,5.93,4.78,9.17,0.738,13.73,10.84,11.17,11.0,...,0.827,4.424254,4.09,9.06,16.66,5.99,20.26,16.78,1.753,20.015
2004,16.31,10.347,5.39,5.83,7.99,0.773,12.04,10.2,10.07,9.57,...,0.805,4.416583,4.19,8.59,12.98,5.53,20.037,15.07,1.763,19.866
2005,15.97,10.218,5.03,5.63,7.26,0.832,10.08,10.2,10.55,9.08,...,0.856,4.495868,4.259,7.18,12.01,5.08,19.757,10.66,1.737,19.744
2006,15.63,10.001,4.78,5.24,6.62,0.859,8.95,7.54,9.69,8.73,...,0.912,4.390292,4.23,6.81,10.84,4.62,19.278,8.61,1.672,19.635
2007,15.97,9.81,4.38,4.86,6.33,0.886,6.88,7.88,9.28,7.41,...,0.924,4.368078,3.815,6.35,9.4,4.62,19.071,7.28,1.799,19.543
2008,13.06,9.997,4.23,4.13,5.86,0.935,5.61,8.18,8.27,8.12,...,0.943,4.455837,3.329,6.36,8.03,5.78,18.79,6.25,1.741,19.51
2009,13.67,9.894,5.56,5.3,5.74,0.996,6.82,14.25,9.42,10.02,...,0.958,4.439853,2.875,8.84,7.74,9.25,18.917,6.1,1.804,20.51
2010,14.09,10.542,5.21,4.82,5.63,1.04,10.28,14.321,8.034,10.69,...,0.952,4.175097,2.427,8.1,7.16,9.63,18.977,7.11,1.85,23.18
2011,13.48,10.917,5.08,4.56,5.42,2.65,11.26,14.52,7.58,11.19,...,1.005,4.124899,1.98,7.85,6.31,8.95,18.919,6.9,1.801,21.42
2012,13.38,11.298,5.22,4.87,5.19,2.454,12.27,14.02,7.25,11.59,...,1.0,4.063379,2.034,7.53,6.45,8.07,18.893,6.6,1.849,21.79
2013,15.87,11.531,5.66,5.34,4.97,2.254,12.94,16.18,7.07,11.55,...,1.027,4.064153,2.09,7.17,6.44,7.37,18.905,7.54,1.859,22.04
2014,18.05,11.862,6.08,5.62,4.91,2.111,11.42,13.8,6.76,12.17,...,1.042,4.060864,2.145,9.27,6.55,6.17,18.948,6.865,1.792,22.61
2015,17.19,12.177,6.05,5.72,4.96,2.023,9.14,12.0,8.56,9.8,...,1.072,4.136945,2.2,9.14,7.49,5.28,18.969,6.077,1.855,22.87
2016,15.42,12.426,5.71,6.01,5.0,1.836,7.57,12.7,11.74,8.25,...,1.118,4.052255,2.965,9.35,7.84,4.87,18.978,5.32,1.749,24.02
2017,13.62,12.944,5.59,5.5,4.96,1.643,6.16,9.8,12.93,8.62,...,1.127,3.931049,3.74,9.5,7.89,4.36,19.028,5.05,1.71,23.99
2018,12.3,13.21,5.3,4.85,4.94,1.47,5.21,10.0,12.46,8.32,...,1.13,3.82428,3.723,8.8,8.34,3.9,19.02,5.02,1.784,24.22
2019,11.47,12.2,5.16,4.49,4.85,1.466,4.23,10.051,12.05,8.41,...,1.12,3.911265,3.707,8.19,8.73,3.67,19.09,5.092,1.757,25.54
2020,13.067,12.18,6.46,5.36,7.16,1.671,5.12,12.867,13.93,10.105,...,1.645,4.384423,4.028,9.48,10.33,8.05,20.55,7.53,2.017,24.34
2021,12.683,12.729,5.12,6.18,5.95,1.752,5.27,11.665,13.34,9.582,...,1.538,4.094142,4.175,9.83,9.29,5.35,20.398,6.471,2.118,28.77

In [23]:
unemployment_remaining_countries.columns

Index(['Country Name', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021'],
      dtype='object')

In [24]:
u = unemployment_remaining_countries.set_index('Country Name').T.columns.tolist()
c = crime_pre_cleaned_filled.set_index('Country Name').T.columns.tolist()
temp = [x for x in c if x not in u]
print(temp)

['Bermuda', 'Cayman Islands', 'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gibraltar', 'Not classified', 'Liechtenstein', 'Monaco', 'Northern Mariana Islands', 'Nauru', 'San Marino', 'Sint Maarten (Dutch part)']

In [25]:
crime_skim = crime_pre_cleaned_filled.set_index('Country Name').T
crime_skim.drop(columns = ['Bermuda', 'Cayman Islands', 'Faroe Islands', 'Micronesia, Fed. Sts.', 'Gibraltar', 'Not classified', 'Liechtenstein', 'Monaco', 'Northern Mariana Islands', 'Nauru', 'San Marino', 'Sint Maarten (Dutch part)'], inplace = True)
crime_skim

Country Name,Albania,Armenia,Australia,Austria,Azerbaijan,Benin,Bulgaria,"Bahamas, The",Brazil,Barbados,...,Chad,East Asia & Pacific (IDA & IBRD countries),Togo,Ukraine,Uruguay,United States,St. Vincent and the Grenadines,"Venezuela, RB",Vanuatu,South Africa
1991,7.469486,5.141486,1.968608,1.328066,4.735836,7.469486,4.299640,10.142814,18.357327,8.095543,...,7.469486,7.469486,7.469486,5.124551,6.187460,9.819916,15.960277,12.370086,7.469486,7.469486
1992,3.934936,8.532529,1.723693,1.237116,7.378975,8.189933,5.329617,14.540425,16.656003,8.454628,...,8.189933,8.189933,8.189933,6.507657,5.770941,9.311245,15.898041,15.777427,8.189933,8.189933
1993,5.786633,7.751603,1.888664,1.011982,6.175625,8.509661,5.690042,12.145840,17.680255,8.046116,...,8.509661,8.509661,8.509661,7.138109,8.509661,9.477558,12.321666,20.271962,8.509661,8.509661
1994,3.400123,4.653626,1.797197,1.108960,6.379541,10.776662,5.755419,17.687285,18.543499,7.642003,...,10.776662,10.776662,10.776662,8.202011,10.776662,8.893766,11.409163,21.870692,10.776662,60.009733
1995,7.885849,3.491050,1.977448,0.981466,5.615179,10.797970,5.827135,13.353185,20.793213,6.481042,...,10.797970,10.797970,10.797970,8.630809,5.953309,8.132935,17.517123,20.269336,10.797970,61.103416
1996,8.314658,3.455700,1.943790,1.244025,5.032015,10.087810,5.213432,16.725013,23.424882,10.087810,...,10.087810,10.087810,10.087810,9.672811,6.353371,7.303399,20.999121,21.978450,10.087810,57.028853
1997,40.999238,3.056778,1.977159,0.828408,3.549973,9.990271,4.784249,14.830553,24.033101,9.990271,...,9.990271,9.990271,9.990271,8.433435,7.488285,6.684400,7.875635,18.339615,9.990271,54.070826
1998,20.419683,2.869883,1.795538,0.965413,3.482113,8.835399,4.626635,8.835399,24.526455,7.586059,...,8.835399,8.835399,8.835399,8.432860,7.478508,6.153678,21.022297,19.358556,8.835399,54.800028
1999,16.582197,2.807211,2.047775,0.750809,2.987120,8.600639,4.006223,8.600639,24.736250,8.706531,...,8.600639,8.600639,8.600639,8.617173,6.587449,5.559822,12.281294,24.925982,8.600639,48.752627
2000,4.116881,2.872000,1.903464,1.023666,2.759349,9.067588,4.099934,22.768250,25.799761,7.556951,...,9.067588,9.067588,9.067588,9.038507,6.500164,5.519150,17.572762,32.839730,9.067588,46.478279
2001,6.976128,2.808690,1.802771,0.870687,2.632207,9.149481,3.833296,13.045087,26.908980,9.420578,...,9.149481,9.149481,9.149481,10.025915,6.604181,6.667239,10.559569,31.993308,9.149481,45.321045
2002,6.915206,2.222195,1.879251,0.804556,2.532212,9.512118,3.197568,15.568769,27.543724,9.382447,...,9.512118,9.512118,9.512118,8.954377,6.986364,5.628225,17.628989,37.965446,9.512118,45.220972
2003,5.366973,10.690800,1.533073,0.615756,10.690800,10.690800,3.119577,14.771463,27.960468,12.336495,...,10.690800,10.690800,10.690800,8.488489,5.951298,10.690800,15.913994,43.991884,10.690800,41.210669
2004,4.277380,2.707335,1.319946,0.722047,9.829372,9.829372,3.102227,12.824642,26.198281,8.193516,...,9.829372,9.829372,9.829372,7.378027,6.035365,9.829372,25.753169,37.057334,9.829372,38.703708
2005,5.078094,1.903358,1.283975,0.656373,9.858969,9.858969,2.546313,14.950949,25.478415,10.761586,...,9.858969,9.858969,9.858969,6.458818,5.726919,9.858969,23.205480,37.362033,9.858969,37.799017
2006,3.163096,2.610288,1.372940,0.737805,9.302158,9.302158,2.395044,17.296893,26.037932,12.942566,...,9.302158,9.302158,9.302158,6.348654,6.080158,5.774419,17.949052,45.225310,9.302158,38.604409
2007,3.528127,2.562914,1.224147,0.542514,2.128759,9.218121,2.293033,21.808025,25.018942,9.210003,...,9.218121,9.218121,9.218121,5.713290,5.828188,5.657597,36.093265,47.796379,9.218121,36.802875
2008,3.150738,3.251302,1.228358,0.697021,2.133405,9.290090,2.241068,20.121556,26.020863,8.436172,...,9.290090,9.290090,9.290090,5.353545,6.624451,5.386089,14.503855,52.226989,9.290090,35.763294
2009,2.900488,3.272277,1.214170,0.611296,10.005086,10.005086,1.964705,23.637675,26.455711,6.939587,...,10.005086,10.005086,10.005086,4.884017,6.758058,4.991377,20.939644,49.368305,10.005086,32.766748
2010,4.084575,1.900694,1.049086,0.729418,2.230112,9.961384,1.949350,25.182709,26.630033,11.284586,...,9.961384,9.961384,9.961384,4.351726,6.114564,4.730981,22.871258,45.551071,9.961384,30.690401
2011,4.895448,2.424055,1.109271,0.917628,2.254511,10.055472,1.696908,33.602328,26.355638,9.800843,...,10.055472,10.055472,10.055472,10.055472,5.919734,4.670944,10.055472,48.453131,10.055472,29.658684
2012,5.428407,2.230289,1.069106,0.960896,2.129549,8.910891,1.882926,28.791214,28.197143,7.965315,...,8.910891,2.100000,8.910891,5.144669,7.920187,4.691596,8.910891,54.536029,8.910891,30.507084
2013,4.295095,2.171377,1.060065,0.719379,2.298617,8.430357,1.466795,30.856995,28.179904,8.668485,...,8.430357,8.430357,8.430357,8.430357,7.689622,4.483442,8.430357,8.430357,8.430357,31.598028
2014,4.646160,2.491410,1.035383,0.491454,2.422530,8.631802,1.519233,31.351910,29.358647,9.009236,...,8.631802,1.500000,8.631802,6.301487,7.901732,4.398294,8.631802,63.027315,8.631802,32.532699
2015,2.220310,2.605438,0.990754,0.509117,2.139204,8.224460,1.723842,37.178744,28.356406,11.147751,...,8.224460,1.400000,8.224460,8.224460,8.610512,4.892982,8.224460,51.274634,8.224460,33.418340
2016,2.742043,3.035764,0.938183,0.618097,1.694024,8.945892,1.090261,28.031967,29.589154,7.895237,...,8.945892,8.945892,8.945892,8.945892,7.821274,5.321656,37.749204,56.623849,8.945892,33.703002
2017,2.014340,2.454484,0.845861,0.795681,1.807067,1.127497,1.434055,30.574909,30.593037,10.745486,...,8.701136,8.701136,8.701136,6.160253,8.269533,5.243924,36.949838,47.982175,8.701136,35.903188
2018,2.294046,1.762700,0.884735,0.972794,1.940405,7.785687,1.292601,22.642082,26.636013,10.011137,...,7.785687,7.785687,7.785687,4.504246,12.284647,4.929848,32.294679,7.785687,7.785687,36.662249
2019,2.261748,2.588100,0.887323,0.867123,1.641787,7.431064,1.176882,23.482476,20.810464,17.131874,...,7.431064,7.431064,7.431064,4.116614,11.492213,4.985947,18.108431,40.984846,0.657021,36.712138
2020,2.127772,1.853430,0.860925,0.729699,2.236277,7.337659,0.988656,17.959439,22.384065,14.606706,...,7.337659,7.337659,7.337659,3.867030,9.856853,6.420751,31.538958,29.427401,0.320837,33.964874
2021,2.311969,2.185617,0.744567,0.728530,1.910212,8.096185,1.277980,29.173424,8.096185,11.379821,...,8.096185,8.096185,8.096185,3.843201,8.901836,6.807466,30.671318,19.305056,8.096185,41.865728

In [26]:
crime_final = crime_skim.T.reset_index()
crime_final

,Country Name,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Albania,7.469486,3.934936,5.786633,3.400123,7.885849,8.314658,40.999238,20.419683,16.582197,...,5.428407,4.295095,4.646160,2.220310,2.742043,2.014340,2.294046,2.261748,2.127772,2.311969
1,Armenia,5.141486,8.532529,7.751603,4.653626,3.491050,3.455700,3.056778,2.869883,2.807211,...,2.230289,2.171377,2.491410,2.605438,3.035764,2.454484,1.762700,2.588100,1.853430,2.185617
2,Australia,1.968608,1.723693,1.888664,1.797197,1.977448,1.943790,1.977159,1.795538,2.047775,...,1.069106,1.060065,1.035383,0.990754,0.938183,0.845861,0.884735,0.887323,0.860925,0.744567
3,Austria,1.328066,1.237116,1.011982,1.108960,0.981466,1.244025,0.828408,0.965413,0.750809,...,0.960896,0.719379,0.491454,0.509117,0.618097,0.795681,0.972794,0.867123,0.729699,0.728530
4,Azerbaijan,4.735836,7.378975,6.175625,6.379541,5.615179,5.032015,3.549973,3.482113,2.987120,...,2.129549,2.298617,2.422530,2.139204,1.694024,1.807067,1.940405,1.641787,2.236277,1.910212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,United States,9.819916,9.311245,9.477558,8.893766,8.132935,7.303399,6.684400,6.153678,5.559822,...,4.691596,4.483442,4.398294,4.892982,5.321656,5.243924,4.929848,4.985947,6.420751,6.807466
96,St. Vincent and the Grenadines,15.960277,15.898041,12.321666,11.409163,17.517123,20.999121,7.875635,21.022297,12.281294,...,8.910891,8.430357,8.631802,8.224460,37.749204,36.949838,32.294679,18.108431,31.538958,30.671318
97,"Venezuela, RB",12.370086,15.777427,20.271962,21.870692,20.269336,21.978450,18.339615,19.358556,24.925982,...,54.536029,8.430357,63.027315,51.274634,56.623849,47.982175,7.785687,40.984846,29.427401,19.305056
98,Vanuatu,7.469486,8.189933,8.509661,10.776662,10.797970,10.087810,9.990271,8.835399,8.600639,...,8.910891,8.430357,8.631802,8.224460,8.945892,8.701136,7.785687,0.657021,0.320837,8.096185
99,South Africa,7.469486,8.189933,8.509661,60.009733,61.103416,57.028853,54.070826,54.800028,48.752627,...,30.507084,31.598028,32.532699,33.418340,33.703002,35.903188,36.662249,36.712138,33.964874,41.865728

In [27]:
unemployment_final = unemployment_remaining_countries.reset_index(drop = True)
unemployment_final

,Country Name,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Albania,10.307,30.015,25.258,20.840,14.611,13.931,16.876,20.047,20.840,...,13.380,15.870,18.050,17.190,15.420,13.620,12.300,11.470,13.067,12.683
1,Armenia,1.600,1.800,5.300,6.600,6.700,9.300,10.800,9.400,11.200,...,11.298,11.531,11.862,12.177,12.426,12.944,13.210,12.200,12.180,12.729
2,Australia,9.580,10.730,10.870,9.720,8.470,8.510,8.360,7.680,6.870,...,5.220,5.660,6.080,6.050,5.710,5.590,5.300,5.160,6.460,5.120
3,Austria,3.420,3.590,4.250,3.540,4.340,5.280,5.150,5.480,4.700,...,4.870,5.340,5.620,5.720,6.010,5.500,4.850,4.490,5.360,6.180
4,Azerbaijan,0.900,1.800,4.500,6.300,7.200,8.100,9.100,10.000,10.900,...,5.190,4.970,4.910,4.960,5.000,4.960,4.940,4.850,7.160,5.950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,United States,6.800,7.500,6.900,6.120,5.650,5.450,5.000,4.510,4.220,...,8.070,7.370,6.170,5.280,4.870,4.360,3.900,3.670,8.050,5.350
96,St. Vincent and the Grenadines,19.770,19.734,19.802,20.185,20.059,20.395,20.471,20.596,20.781,...,18.893,18.905,18.948,18.969,18.978,19.028,19.020,19.090,20.550,20.398
97,"Venezuela, RB",9.450,7.690,6.600,8.560,10.240,11.770,11.160,11.150,14.530,...,6.600,7.540,6.865,6.077,5.320,5.050,5.020,5.092,7.530,6.471
98,Vanuatu,1.734,1.751,1.797,1.622,1.800,1.773,1.719,1.808,1.832,...,1.849,1.859,1.792,1.855,1.749,1.710,1.784,1.757,2.017,2.118
99,South Africa,21.194,21.159,20.971,20.828,20.750,20.627,20.595,20.573,20.419,...,21.790,22.040,22.610,22.870,24.020,23.990,24.220,25.540,24.340,28.770

In [28]:
# Save transformed and transposed data to CSV files
unemployment_final.to_csv(r'D:\Github\made-ws23\project\data\data\unemployment.csv', index=False)
crime_final.to_csv(r'D:\Github\made-ws23\project\data\data\crime.csv', index=False)